### ISSUE TITLE
EPIC: deephaven.ui

### ISSUE THREAD

**Issue by mofojed** [deephaven/deephaven-plugins#50]
Epic ticket for the deephaven.ui framework for programmatic layouts and callbacks.

## General:
- [x] Discuss requirements with team in [Requirements Doc](https://docs.google.com/document/d/1XtPXVMxgeQaIwWLvyoTIcNklqToS4rsTlcFe-7Mvp0I).
- [x] #47 

## Python:
All features require pydocs and examples for each item.
- [x] #51
- [x] #52
- [x] #53
- [x] #54
- [x] #55
- [x] #61
- [x] #63
- [x] #67
- [ ] Create ui.pq_table component (some way to reference other table from another PQ that resolves on the client)
- [x] #56
- [x] #96 
- [x] #97
- [x] #116

## JavaScript:
- [x] #57
- [x] #58
- [x] #59
- [x] #75
- [ ] Update Linker to allow setting links between components (instead of just panels)
- [ ] #92
- [x] #60
- [ ] #166

## Communication:
- [ ] #81
- [x] #85
- [x] #123
- [x] #128

## Other Components:
- [ ] #77
- [x] #62 
- [ ] #120
- [x] #76 
- [x] #933
- [ ] Popover?
- [x] Form
- [x] #937
- [x] Text input (Text Field - need to decide between input or field nomenclature)
- [x] #649
- [x] Button
- [x] Action button
- [x] Toggle Button
- [x] Switch
- [x] Slider
- [x] Range slider
- [x] Checkbox
- [x] #620
- [x] Radio group
- [x] Number Field
- [x] #763
- [ ] Data input
- [x] #367 
- [x] #648
- [x] #764
- [x] #670 
- [ ] Video
- [x] #335
- [x] #826
- [x] #935
- [x] #977
- [x] #127
- [ ] Details/Summary Expander
- [x] #201
- [x] #200
- [ ] TagGroup, TagGroup with picker?
- [x] Text
- [ ] Pretty print/collapsible JSON viewer
- [x] #890
- [ ] Mermaid diagrams
- [x] Raw HTML (mostly just for formatting text, but unsafe/dangerously set html?)
- [x] Heading
- [ ] Download Button (creates a file)
- [x] #134
- [ ] Console/IDE Component
- [ ] Shortcuts? On components? On the dashboard?
- [ ] scroll_area (view with overflow=auto, height=100%)
- [ ] #362
- [x] #905
- [x] #904
- [x] #936
- [x] #938
- [x] #939
- [x] #940
- [x] #941
- [x] #1037
- [x] #410
- [x] #1033
- [ ] #1034
- [x] #1035
- [x] #1036
- [x] #1038

**Comment by kzk2000** [comment]
@mofojed as you suggested, posting my wish list of how to prioritize here, most important on top:

1. ui.picker
2. ui.table  left 1-click / left double-click / right-click context menu overwrites
3. Datetime input and/or Range Calendar
4. Markdown / Heading / Divider -> make the page look great
5. Menu

**Comment by dsmmcken** [comment]
Recent top enterprise requests:
- ~list_view~ (now available)
- combo_box
- ui.table_view -> context menu, freeze column, formatting
- ui.flex examples/docs (customer had normal flexbox challenges and would like to see more examples)
- ability to turn off headers on ui.panel/ui.stacks
- dx.denisty_heatmap
- ui.modals
